services:
  - type: static_site
    name: kasec-evoting
    buildCommand: 'cd evoting-frontend && npm install && npm run build'
    staticPublishPath: 'evoting-frontend/dist'
    envVars:
      - key: VITE_API_BASE_URL
        value: https://evoting-kasec.up.railway.app/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
